#!/bin/bash
apt-get update
apt-get install obexftp bluez -y

cat <<EOF > /etc/systemd/system/obexftpd.service
[Unit]
Description=Obexftpd Service
After=bluetooth.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu
ExecStart=/home/ubuntu/run_obexftpd.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

cat << EOF > /home/ubuntu/run_obexftpd.sh
#!/bin/bash

pkill -f obex-data-server

cd ~

if [ ! -d ".obexftp" ]
then
    echo "no directory, creating.."
    mkdir ~/.obexftp
    chmod 775 ~/.obexftp
fi

sudo hciconfig hci0 up
sudo hciconfig hci0 piscan
sudo obexftpd -c ~/.obexftp -b | tee /tmp/obexftpd.log
EOF
chmod +x /home/ubuntu/run_obexftpd.sh

# Need this to regisger SDP service
sed -ie 's/ExecStart=\/usr\/lib\/bluetooth\/bluetoothd/ExecStart=\/usr\/lib\/bluetooth\/bluetoothd\ --compat/g' /lib/systemd/system/bluetooth.service
systemctl daemon-reload
systemctl restart bluetooth.service

systemctl enable obexftpd.service

