#!/bin/bash
apt-get update
apt-get install git -y
touch /tai-charm2-1
cat <<EOF > /etc/systemd/system/obexftpd.service
[Unit]
Description=Obexftpd Service
After=bluetooth.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu
ExecStart=/home/ubuntu/run_obexftpd.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

cat << EOF > /home/ubuntu/run_obexftpd.sh
#!/bin/bash

pkill -f obex-data-server

cd ~

if [ ! -d ".obexftp" ]
then
            echo "no directory, creating.."
                mkdir ~/.obexftp
                    chmod 775 ~/.obexftp
            fi

            obexftpd -c ~/.obexftp -b
EOF
touch /tai-charm2-2
apt-get install obexftp

systemctl enable obexftpd.service

